### ISSUE TITLE
Anki 2.1?

### ISSUE THREAD

**Issue by thatstheway** [robbielaldrich/ankiTypebox#2]
I'm in medical school and I love the idea of this plug-in! I have been writing out notes on answers by hand and I'd love to be able to quickly type them directly onto my card. Any plans to make this compatible with Anki 2.1?

**Comment by GGArdrey** [comment]
Hi, I did an update to anki 2.1, for a friend also in medical school :D  I reuploaded it to https://ankiweb.net/shared/info/335425447

hope its okay for @robbielaldrich

**Comment by robbielaldrich** [comment]
Yes, thank you!

**Comment by Mattzus** [comment]
@robbiealdrich
Unfortunately the update for 2.1 is not working properly
The textbox appears but if you look up the answer the text you typen into the textbox disappears

Maybe you have an idea how to solve this issue?

**Comment by robbielaldrich** [comment]
@Mattzus @thatstheway I just made a new version for 2.1, please check it out and let me know what you think. Add-on number 681236951

**Comment by robbielaldrich** [comment]
Updated usage details: https://ankiweb.net/shared/info/681236951

**Comment by thatstheway** [comment]
Just wanted to follow up on this - it is amazing!!! If I’m just using [[typebox:]] and not using any “correction” on the answer I input, is there a way to format the text of my answer that displays on the back of the card? It defaults to Arial I’d like to make it match the rest of my card which is in Georgia.

The fact that the text displays when you flip the card is so great … this is the way every student should be studying! Really forces you to demonstrate to yourself what you know.

Thanks!

**Comment by robbielaldrich** [comment]
Great! Thanks for pointing that out, I see the need to use the font defined in the ".card {}" styling (I guess that's what you're doing?). I just pushed an update, try clicking "Check for Updates" in the Add-ons menu and try your note again. I'm now working to allow also specifying 'font-family' and 'font-size' in new classes '.textbox-input' and '.textbox-output'.

**Comment by thatstheway** [comment]
That’s awesome!! I’ll try it out shortly. Thanks!
