### ISSUE TITLE
'ImportRule' object has no attribute 'selector'

### ISSUE THREAD

**Issue by kodezen** [robbielaldrich/ankiTypebox#3]
Getting this error whenever I try to review Anki cards today (I'm on latest updated version of Typebox)

Debug info:
Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-04-25 17:47:48

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 446, in handler
  File "aqt\reviewer.py", line 542, in _onTypedAnswer
  File "aqt\reviewer.py", line 241, in _showAnswer
  File "aqt\reviewer.py", line 174, in _mungeQA
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\681236951\__init__.py", line 15, in typeboxAnsFilter
    typebox_replaced = self.typeboxAnsAnswerFilter(buf)
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\681236951\__init__.py", line 109, in typeboxAnsAnswerFilter
    _set_font_details_from_card(self, parsed_style, ".textbox-output-parent")
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\681236951\__init__.py", line 25, in _set_font_details_from_card
    card_style = next(
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\681236951\__init__.py", line 26, in <genexpr>
    (r for r in style.rules if "".join([t.value for t in r.selector]) == selector), None)
AttributeError: 'ImportRule' object has no attribute 'selector'

My other addons (not sure if this list in issue report but figured I'd include anyway in case it can help):
- Copy notes
- Opening the same window multiple time
- Keep model of add cards
- Pokemanki
- Progress Bar
- Resize images in editor
- Review Heatmap
- syntax highlighting FORK
- True Retention

Any idea what might be causing this error?

**Comment by robbielaldrich** [comment]
Hey, I actually wasn't able to reproduce that error, even after downloading those add-ons. I have one thought about how there could be an issue - maybe some other addon is using a python module with the same name as one that I included (tinycss) but from a different version. I just made another version of the addon to try to get around this, so click "check for updates" in the addon menu and try your notes again.

**Comment by kodezen** [comment]
Thanks a bunch for looking into this, I really appreciate it! I updated to the newest version and still was experiencing the error. I went ahead and disabled all add-ons except for Typebox and still got the same error. Very strange. Going to try uninstall and reinstalling the add-on to see if that fixes it. Will report back!

**Comment by kodezen** [comment]
Hmm so even after reinstalling it with Typebox I was still getting the same issue. Not sure what underlying issue was causing the rule not to have a selector attribute, but I was able to get the input cards working again by checking for the attribute with hasattr(...)

**Comment by robbielaldrich** [comment]
Ah of course, you must have some "import" rules in your CSS. I'll update the addon with a fix like yours.

**Comment by kodezen** [comment]
Awesome thank you so much! And yep you're totally right had some @import's added by syntax highlighter and image resizer addon
