### ISSUE TITLE
Wrap text for input answer on back of card?

### ISSUE THREAD

**Issue by thatstheway** [robbielaldrich/ankiTypebox#4]
I think this is just a styling thing on my end but when I input a few lines of text into the answer box and then flip the card, the text I input that is then, very helpfully, displayed on the back of the card, doesn't wrap and so rather runs off the right side of the card. Is there something I need to do to style that such that it is centered and creates a line break at a certain point?

Thank you!
<img width="1920" alt="Screen Shot 2020-04-29 at 6 43 45 PM" src="https://user-images.githubusercontent.com/37633100/80654207-c294d180-8a49-11ea-8ffc-7678fec3f531.png">

**Comment by robbielaldrich** [comment]
Hi, you can add this to your styling:
`.textbox-output {
    white-space: pre-wrap;
}`

**Comment by thatstheway** [comment]
Thank you!!
