### ISSUE TITLE
Cloze deletions?

### ISSUE THREAD

**Issue by thatstheway** [robbielaldrich/ankiTypebox#5]
Should this work on cloze deletion cards as well? I am able to get the typebox to appear on the front of the card but can't figure out how to get it to display on the back of the card as the elements are different than the basic card.

Thanks!

**Comment by robbielaldrich** [comment]
Hi, yes, just add `[[typebox:]]` to the back of the card as well as the front.

**Comment by thatstheway** [comment]
Amazing - thanks!!!
